export enum TransactionTopics {
  HANDLE_TRANSACTION_CREATED = 'HANDLE_TRANSACTION_CREATED',
  HANDLE_TRANSACTION_CHANGED = 'HANDLE_TRANSACTION_CHANGED',
  HANDLE_TRANSACTION_DELETED = 'HANDLE_TRANSACTION_DELETED',
}
